// <auto-generated />
namespace Excel.Web.DataContexts.ExcelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SessionData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SessionData));
        
        string IMigrationMetadata.Id
        {
            get { return "201506070544430_SessionData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
