// <auto-generated />
namespace Excel.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddAthleteTypeToSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAthleteTypeToSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201507312357227_AddAthleteTypeToSession"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
